; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.24234.1 

include listing.inc

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

PUBLIC	?hInstance@@3PEAUHINSTANCE__@@EA		; hInstance
PUBLIC	WinbaseIsolationAwarePrivateT_UnPgpgk
PUBLIC	IsolationAwarePrivateT_SqbjaYRiRY
PUBLIC	IsolationAwarePrivateT_SAbnPgpgk
PUBLIC	WinbaseIsolationAwarePrivateT_SpeRNgRQnPgpgk
PUBLIC	WinbaseIsolationAwarePrivateT_SpYRNahcpNYYRQ
PUBLIC	?controlsInit@@3HA				; controlsInit
EXTRN	GUID_NULL:BYTE
_BSS	SEGMENT
?hInstance@@3PEAUHINSTANCE__@@EA DQ 01H DUP (?)		; hInstance
_BSS	ENDS
;	COMDAT IsolationAwarePrivateT_SqbjaYRiRY
_BSS	SEGMENT
IsolationAwarePrivateT_SqbjaYRiRY DD 01H DUP (?)
_BSS	ENDS
;	COMDAT IsolationAwarePrivateT_SAbnPgpgk
_BSS	SEGMENT
IsolationAwarePrivateT_SAbnPgpgk DD 01H DUP (?)
_BSS	ENDS
;	COMDAT WinbaseIsolationAwarePrivateT_SpeRNgRQnPgpgk
_BSS	SEGMENT
WinbaseIsolationAwarePrivateT_SpeRNgRQnPgpgk DD 01H DUP (?)
_BSS	ENDS
;	COMDAT WinbaseIsolationAwarePrivateT_SpYRNahcpNYYRQ
_BSS	SEGMENT
WinbaseIsolationAwarePrivateT_SpYRNahcpNYYRQ DD 01H DUP (?)
_BSS	ENDS
_BSS	SEGMENT
?controlsInit@@3HA DD 01H DUP (?)			; controlsInit
_BSS	ENDS
;	COMDAT WinbaseIsolationAwarePrivateT_UnPgpgk
_DATA	SEGMENT
WinbaseIsolationAwarePrivateT_UnPgpgk DQ ffffffffffffffffH
_DATA	ENDS
PUBLIC	??_H@YAXPEAX_K1P6APEAX0@Z@Z			; `vector constructor iterator'
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	IsolationAwarePrivatezlybNQyVOeNelJ
PUBLIC	IsolationAwarePrivatenPgViNgRzlnPgpgk
PUBLIC	WinbaseIsolationAwarePrivatetRgzlnPgpgk
PUBLIC	CommctrlIsolationAwarePrivatetRgCebPnQQeRff_pbZPgYQP_QYY
PUBLIC	IsolationAwareInitCommonControls
PUBLIC	?GetString@@YAPEA_WH@Z				; GetString
PUBLIC	DllMain
PUBLIC	?LibNumberClasses@@YAHXZ			; LibNumberClasses
PUBLIC	?LibClassDesc@@YAPEAVClassDesc@@H@Z		; LibClassDesc
PUBLIC	?LibDescription@@YAPEB_WXZ			; LibDescription
PUBLIC	?LibVersion@@YAKXZ				; LibVersion
PUBLIC	?LibInitialize@@YAHXZ				; LibInitialize
PUBLIC	?LibShutdown@@YAHXZ				; LibShutdown
PUBLIC	??_C@_1BK@BFMCNHEO@?$AAC?$AAo?$AAm?$AAc?$AAt?$AAl?$AA3?$AA2?$AA?4?$AAd?$AAl?$AAl?$AA?$AA@ ; `string'
PUBLIC	?debugString@?4??IsolationAwarePrivatenPgViNgRzlnPgpgk@@9@4QBDB ; `IsolationAwarePrivatenPgViNgRzlnPgpgk'::`5'::debugString
PUBLIC	?s_pfn@?1??IsolationAwareInitCommonControls@@9@4P6AXXZEA ; `IsolationAwareInitCommonControls'::`2'::s_pfn
PUBLIC	??_C@_0BD@KDNHKDOA@InitCommonControls?$AA@	; `string'
PUBLIC	?c@?1??CommctrlIsolationAwarePrivatetRgCebPnQQeRff_pbZPgYQP_QYY@@9@4UIsolationAwarePrivate_pBAFGnAG_zBqHyr_vAsB@@B ; `CommctrlIsolationAwarePrivatetRgCebPnQQeRff_pbZPgYQP_QYY'::`2'::c
PUBLIC	?m@?1??CommctrlIsolationAwarePrivatetRgCebPnQQeRff_pbZPgYQP_QYY@@9@4UIsolationAwarePrivate_zHGnoyr_zBqHyr_vAsB@@A ; `CommctrlIsolationAwarePrivatetRgCebPnQQeRff_pbZPgYQP_QYY'::`2'::m
EXTRN	__imp_OutputDebugStringA:PROC
EXTRN	__imp_GetLastError:PROC
EXTRN	__imp_SetLastError:PROC
EXTRN	__imp_DisableThreadLibraryCalls:PROC
EXTRN	__imp_GetModuleFileNameW:PROC
EXTRN	__imp_GetModuleHandleExW:PROC
EXTRN	__imp_GetProcAddress:PROC
EXTRN	__imp_LoadStringW:PROC
EXTRN	__imp_LoadLibraryW:PROC
EXTRN	__imp_CreateActCtxW:PROC
EXTRN	__imp_ActivateActCtx:PROC
EXTRN	__imp_DeactivateActCtx:PROC
EXTRN	__imp_FindActCtxSectionStringW:PROC
EXTRN	__imp_QueryActCtxW:PROC
EXTRN	__imp_?UseLanguagePackLocale@Util@MaxSDK@@YAXPEAUHINSTANCE__@@@Z:PROC
EXTRN	?GetBerconNoiseDesc@@YAPEAVClassDesc2@@XZ:PROC	; GetBerconNoiseDesc
EXTRN	?GetBerconWoodDesc@@YAPEAVClassDesc2@@XZ:PROC	; GetBerconWoodDesc
EXTRN	?GetBerconTileDesc@@YAPEAVClassDesc2@@XZ:PROC	; GetBerconTileDesc
EXTRN	?GetBerconDistortionDesc@@YAPEAVClassDesc2@@XZ:PROC ; GetBerconDistortionDesc
EXTRN	?GetBerconGradientDesc@@YAPEAVClassDesc2@@XZ:PROC ; GetBerconGradientDesc
EXTRN	?InitGradientControls@@YAXXZ:PROC		; InitGradientControls
EXTRN	__C_specific_handler:PROC
EXTRN	__ImageBase:BYTE
;	COMDAT ?s_pfn@?1??IsolationAwareInitCommonControls@@9@4P6AXXZEA
_BSS	SEGMENT
?s_pfn@?1??IsolationAwareInitCommonControls@@9@4P6AXXZEA DQ 01H DUP (?) ; `IsolationAwareInitCommonControls'::`2'::s_pfn
_BSS	ENDS
;	COMDAT ?m@?1??CommctrlIsolationAwarePrivatetRgCebPnQQeRff_pbZPgYQP_QYY@@9@4UIsolationAwarePrivate_zHGnoyr_zBqHyr_vAsB@@A
_BSS	SEGMENT
?m@?1??CommctrlIsolationAwarePrivatetRgCebPnQQeRff_pbZPgYQP_QYY@@9@4UIsolationAwarePrivate_zHGnoyr_zBqHyr_vAsB@@A DQ 01H DUP (?) ; `CommctrlIsolationAwarePrivatetRgCebPnQQeRff_pbZPgYQP_QYY'::`2'::m
_BSS	ENDS
_BSS	SEGMENT
?kInvalidId@AssetManagement@MaxSDK@@3UAssetId@12@A DB 010H DUP (?) ; MaxSDK::AssetManagement::kInvalidId
_BSS	ENDS
;	COMDAT ?buf@?1??GetString@@YAPEA_WH@Z@4PA_WA
_BSS	SEGMENT
?buf@?1??GetString@@YAPEA_WH@Z@4PA_WA DW 0100H DUP (?)	; `GetString'::`2'::buf
_BSS	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??_H@YAXPEAX_K1P6APEAX0@Z@Z DD imagerel $LN12
	DD	imagerel $LN12+72
	DD	imagerel $unwind$??_H@YAXPEAX_K1P6APEAX0@Z@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$IsolationAwarePrivatenPgViNgRzlnPgpgk DD imagerel $LN21
	DD	imagerel $LN21+138
	DD	imagerel $unwind$IsolationAwarePrivatenPgViNgRzlnPgpgk
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$IsolationAwarePrivatezltRgCebPnQQeRff DD imagerel $LN8
	DD	imagerel $LN8+75
	DD	imagerel $unwind$IsolationAwarePrivatezltRgCebPnQQeRff
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$WinbaseIsolationAwarePrivatetRgzlnPgpgk DD imagerel $LN40
	DD	imagerel $LN40+441
	DD	imagerel $unwind$WinbaseIsolationAwarePrivatetRgzlnPgpgk
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$WinbaseIsolationAwarePrivatetRgzlnPgpgk$fin$0 DD imagerel WinbaseIsolationAwarePrivatetRgzlnPgpgk$fin$0
	DD	imagerel WinbaseIsolationAwarePrivatetRgzlnPgpgk$fin$0+32
	DD	imagerel $unwind$WinbaseIsolationAwarePrivatetRgzlnPgpgk$fin$0
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$CommctrlIsolationAwarePrivatetRgCebPnQQeRff_pbZPgYQP_QYY DD imagerel $LN28
	DD	imagerel $LN28+204
	DD	imagerel $unwind$CommctrlIsolationAwarePrivatetRgCebPnQQeRff_pbZPgYQP_QYY
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$CommctrlIsolationAwarePrivatetRgCebPnQQeRff_pbZPgYQP_QYY$fin$0 DD imagerel CommctrlIsolationAwarePrivatetRgCebPnQQeRff_pbZPgYQP_QYY$fin$0
	DD	imagerel CommctrlIsolationAwarePrivatetRgCebPnQQeRff_pbZPgYQP_QYY$fin$0+82
	DD	imagerel $unwind$CommctrlIsolationAwarePrivatetRgCebPnQQeRff_pbZPgYQP_QYY$fin$0
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$IsolationAwareInitCommonControls DD imagerel $LN39
	DD	imagerel $LN39+226
	DD	imagerel $unwind$IsolationAwareInitCommonControls
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$IsolationAwareInitCommonControls$fin$0 DD imagerel IsolationAwareInitCommonControls$fin$0
	DD	imagerel IsolationAwareInitCommonControls$fin$0+47
	DD	imagerel $unwind$IsolationAwareInitCommonControls$fin$0
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?GetString@@YAPEA_WH@Z DD imagerel $LN5
	DD	imagerel $LN5+18
	DD	imagerel $unwind$?GetString@@YAPEA_WH@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$0$?GetString@@YAPEA_WH@Z DD imagerel $LN5+18
	DD	imagerel $LN5+66
	DD	imagerel $chain$0$?GetString@@YAPEA_WH@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$1$?GetString@@YAPEA_WH@Z DD imagerel $LN5+66
	DD	imagerel $LN5+73
	DD	imagerel $chain$1$?GetString@@YAPEA_WH@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$DllMain DD imagerel $LN7
	DD	imagerel $LN7+83
	DD	imagerel $unwind$DllMain
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?LibDescription@@YAPEB_WXZ DD imagerel $LN8
	DD	imagerel $LN8+16
	DD	imagerel $unwind$?LibDescription@@YAPEB_WXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$0$?LibDescription@@YAPEB_WXZ DD imagerel $LN8+16
	DD	imagerel $LN8+69
	DD	imagerel $chain$0$?LibDescription@@YAPEB_WXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$1$?LibDescription@@YAPEB_WXZ DD imagerel $LN8+69
	DD	imagerel $LN8+77
	DD	imagerel $chain$1$?LibDescription@@YAPEB_WXZ
pdata	ENDS
CRT$XCU	SEGMENT
?kInvalidId$initializer$@AssetManagement@MaxSDK@@3P6AXXZEA DQ FLAT:??__EkInvalidId@AssetManagement@MaxSDK@@YAXXZ ; MaxSDK::AssetManagement::kInvalidId$initializer$
CRT$XCU	ENDS
_DATA	SEGMENT
?kTriObjNormalXTCID@@3VClass_ID@@B DD 0730a33d7H	; kTriObjNormalXTCID
	DD	027246c55H
_DATA	ENDS
;	COMDAT ?c@?1??CommctrlIsolationAwarePrivatetRgCebPnQQeRff_pbZPgYQP_QYY@@9@4UIsolationAwarePrivate_pBAFGnAG_zBqHyr_vAsB@@B
CONST	SEGMENT
?c@?1??CommctrlIsolationAwarePrivatetRgCebPnQQeRff_pbZPgYQP_QYY@@9@4UIsolationAwarePrivate_pBAFGnAG_zBqHyr_vAsB@@B DQ FLAT:IsolationAwarePrivatezlybNQyVOeNelJ ; `CommctrlIsolationAwarePrivatetRgCebPnQQeRff_pbZPgYQP_QYY'::`2'::c
	DQ	FLAT:??_C@_1BK@BFMCNHEO@?$AAC?$AAo?$AAm?$AAc?$AAt?$AAl?$AA3?$AA2?$AA?4?$AAd?$AAl?$AAl?$AA?$AA@
CONST	ENDS
;	COMDAT ??_C@_0BD@KDNHKDOA@InitCommonControls?$AA@
CONST	SEGMENT
??_C@_0BD@KDNHKDOA@InitCommonControls?$AA@ DB 'InitCommonControls', 00H ; `string'
CONST	ENDS
;	COMDAT ?debugString@?4??IsolationAwarePrivatenPgViNgRzlnPgpgk@@9@4QBDB
CONST	SEGMENT
?debugString@?4??IsolationAwarePrivatenPgViNgRzlnPgpgk@@9@4QBDB DB 'Isola'
	DB	'tionAware function called after IsolationAwareCleanup', 0aH, 00H ; `IsolationAwarePrivatenPgViNgRzlnPgpgk'::`5'::debugString
CONST	ENDS
;	COMDAT ??_C@_1BK@BFMCNHEO@?$AAC?$AAo?$AAm?$AAc?$AAt?$AAl?$AA3?$AA2?$AA?4?$AAd?$AAl?$AAl?$AA?$AA@
CONST	SEGMENT
??_C@_1BK@BFMCNHEO@?$AAC?$AAo?$AAm?$AAc?$AAt?$AAl?$AA3?$AA2?$AA?4?$AAd?$AAl?$AAl?$AA?$AA@ DB 'C'
	DB	00H, 'o', 00H, 'm', 00H, 'c', 00H, 't', 00H, 'l', 00H, '3', 00H
	DB	'2', 00H, '.', 00H, 'd', 00H, 'l', 00H, 'l', 00H, 00H, 00H ; `string'
CONST	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$1$?LibDescription@@YAPEB_WXZ DD 021H
	DD	imagerel $LN8
	DD	imagerel $LN8+16
	DD	imagerel $unwind$?LibDescription@@YAPEB_WXZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$0$?LibDescription@@YAPEB_WXZ DD 020521H
	DD	043405H
	DD	imagerel $LN8
	DD	imagerel $LN8+16
	DD	imagerel $unwind$?LibDescription@@YAPEB_WXZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?LibDescription@@YAPEB_WXZ DD 010401H
	DD	04204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$DllMain DD 020601H
	DD	030023206H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$1$?GetString@@YAPEA_WH@Z DD 021H
	DD	imagerel $LN5
	DD	imagerel $LN5+18
	DD	imagerel $unwind$?GetString@@YAPEA_WH@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$0$?GetString@@YAPEA_WH@Z DD 020521H
	DD	043405H
	DD	imagerel $LN5
	DD	imagerel $LN5+18
	DD	imagerel $unwind$?GetString@@YAPEA_WH@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?GetString@@YAPEA_WH@Z DD 010401H
	DD	04204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$IsolationAwareInitCommonControls$fin$0 DD 020601H
	DD	050023206H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$IsolationAwareInitCommonControls DD 020611H
	DD	030023206H
	DD	imagerel __C_specific_handler
	DD	01H
	DD	imagerel $LN39+154
	DD	imagerel $LN39+189
	DD	imagerel IsolationAwareInitCommonControls$fin$0
	DD	00H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$CommctrlIsolationAwarePrivatetRgCebPnQQeRff_pbZPgYQP_QYY$fin$0 DD 040801H
	DD	070043208H
	DD	030025003H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$CommctrlIsolationAwarePrivatetRgCebPnQQeRff_pbZPgYQP_QYY DD 081511H
	DD	0b7415H
	DD	0a6415H
	DD	083415H
	DD	0e0115215H
	DD	imagerel __C_specific_handler
	DD	01H
	DD	imagerel $LN28+41
	DD	imagerel $LN28+127
	DD	imagerel CommctrlIsolationAwarePrivatetRgCebPnQQeRff_pbZPgYQP_QYY$fin$0
	DD	00H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$WinbaseIsolationAwarePrivatetRgzlnPgpgk$fin$0 DD 020601H
	DD	050027206H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$WinbaseIsolationAwarePrivatetRgzlnPgpgk DD 030911H
	DD	05a0109H
	DD	03002H
	DD	imagerel __C_specific_handler
	DD	01H
	DD	imagerel $LN40+352
	DD	imagerel $LN40+409
	DD	imagerel WinbaseIsolationAwarePrivatetRgzlnPgpgk$fin$0
	DD	00H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$IsolationAwarePrivatezltRgCebPnQQeRff DD 040a01H
	DD	06340aH
	DD	07006320aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$IsolationAwarePrivatenPgViNgRzlnPgpgk DD 020601H
	DD	030023206H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??_H@YAXPEAX_K1P6APEAX0@Z@Z DD 081901H
	DD	086419H
	DD	075419H
	DD	063419H
	DD	070153219H
xdata	ENDS
; Function compile flags: /Ogtp
; File g:\dropbox\github\berconmaps\src\dllentry.cpp
;	COMDAT ?LibShutdown@@YAHXZ
_TEXT	SEGMENT
?LibShutdown@@YAHXZ PROC				; LibShutdown, COMDAT

; 126  : 	return TRUE;	

	mov	eax, 1

; 127  : }

	ret	0
?LibShutdown@@YAHXZ ENDP				; LibShutdown
_TEXT	ENDS
; Function compile flags: /Ogtp
; File g:\dropbox\github\berconmaps\src\dllentry.cpp
;	COMDAT ?LibInitialize@@YAHXZ
_TEXT	SEGMENT
?LibInitialize@@YAHXZ PROC				; LibInitialize, COMDAT

; 122  : 	return TRUE;

	mov	eax, 1

; 123  : }

	ret	0
?LibInitialize@@YAHXZ ENDP				; LibInitialize
_TEXT	ENDS
; Function compile flags: /Ogtp
; File g:\dropbox\github\berconmaps\src\dllentry.cpp
;	COMDAT ?LibVersion@@YAKXZ
_TEXT	SEGMENT
?LibVersion@@YAKXZ PROC					; LibVersion, COMDAT

; 118  : 	return VERSION_3DSMAX;

	mov	eax, 1376269312				; 52083400H

; 119  : }

	ret	0
?LibVersion@@YAKXZ ENDP					; LibVersion
_TEXT	ENDS
; Function compile flags: /Ogtp
; File g:\dropbox\github\berconmaps\src\dllentry.cpp
;	COMDAT ?LibDescription@@YAPEB_WXZ
_TEXT	SEGMENT
?LibDescription@@YAPEB_WXZ PROC				; LibDescription, COMDAT

; 112  : {

$LN8:
	sub	rsp, 40					; 00000028H

; 29   : 	if (hInstance)

	mov	rcx, QWORD PTR ?hInstance@@3PEAUHINSTANCE__@@EA ; hInstance
	test	rcx, rcx
	je	SHORT $LN4@LibDescrip
	mov	QWORD PTR [rsp+32], rbx

; 30   : 		return LoadString(hInstance, id, buf, sizeof(buf)) ? buf : NULL;

	mov	r9d, 512				; 00000200H
	lea	rbx, OFFSET FLAT:?buf@?1??GetString@@YAPEA_WH@Z@4PA_WA
	mov	edx, 1
	mov	r8, rbx
	call	QWORD PTR __imp_LoadStringW
	xor	ecx, ecx
	test	eax, eax
	cmovne	rcx, rbx
	mov	rbx, QWORD PTR [rsp+32]

; 113  : 	return GetString(IDS_LIBDESCRIPTION);

	mov	rax, rcx

; 114  : }

	add	rsp, 40					; 00000028H
	ret	0
$LN4@LibDescrip:

; 113  : 	return GetString(IDS_LIBDESCRIPTION);

	mov	rax, rcx

; 114  : }

	add	rsp, 40					; 00000028H
	ret	0
?LibDescription@@YAPEB_WXZ ENDP				; LibDescription
_TEXT	ENDS
; Function compile flags: /Ogtp
; File g:\dropbox\github\berconmaps\src\dllentry.cpp
;	COMDAT ?LibClassDesc@@YAPEAVClassDesc@@H@Z
_TEXT	SEGMENT
i$ = 8
?LibClassDesc@@YAPEAVClassDesc@@H@Z PROC		; LibClassDesc, COMDAT

; 71   : 	switch(i) {

	test	ecx, ecx
	je	SHORT $LN4@LibClassDe
	sub	ecx, 1
	je	SHORT $LN5@LibClassDe
	sub	ecx, 1
	je	SHORT $LN6@LibClassDe
	sub	ecx, 1
	je	SHORT $LN7@LibClassDe
	cmp	ecx, 1
	je	SHORT $LN8@LibClassDe

; 77   : 		default: return 0;

	xor	eax, eax

; 78   : 	}
; 79   : }

	ret	0
$LN8@LibClassDe:

; 76   : 		case 4: return GetBerconGradientDesc();

	jmp	?GetBerconGradientDesc@@YAPEAVClassDesc2@@XZ ; GetBerconGradientDesc
$LN7@LibClassDe:

; 75   : 		case 3: return GetBerconDistortionDesc();

	jmp	?GetBerconDistortionDesc@@YAPEAVClassDesc2@@XZ ; GetBerconDistortionDesc
$LN6@LibClassDe:

; 74   : 		case 2: return GetBerconTileDesc();

	jmp	?GetBerconTileDesc@@YAPEAVClassDesc2@@XZ ; GetBerconTileDesc
$LN5@LibClassDe:

; 73   : 		case 1: return GetBerconWoodDesc();

	jmp	?GetBerconWoodDesc@@YAPEAVClassDesc2@@XZ ; GetBerconWoodDesc
$LN4@LibClassDe:

; 72   : 		case 0: return GetBerconNoiseDesc();

	jmp	?GetBerconNoiseDesc@@YAPEAVClassDesc2@@XZ ; GetBerconNoiseDesc
?LibClassDesc@@YAPEAVClassDesc@@H@Z ENDP		; LibClassDesc
_TEXT	ENDS
; Function compile flags: /Ogtp
; File g:\dropbox\github\berconmaps\src\dllentry.cpp
;	COMDAT ?LibNumberClasses@@YAHXZ
_TEXT	SEGMENT
?LibNumberClasses@@YAHXZ PROC				; LibNumberClasses, COMDAT

; 67   : 	return 5;

	mov	eax, 5

; 68   : }

	ret	0
?LibNumberClasses@@YAHXZ ENDP				; LibNumberClasses
_TEXT	ENDS
; Function compile flags: /Ogtp
; File g:\dropbox\github\berconmaps\src\dllentry.cpp
;	COMDAT DllMain
_TEXT	SEGMENT
hinstDLL$ = 48
fdwReason$ = 56
__formal$ = 64
DllMain	PROC						; COMDAT

; 49   : BOOL WINAPI DllMain(HINSTANCE hinstDLL,ULONG fdwReason,LPVOID /*lpvReserved*/) {

$LN7:
	push	rbx
	sub	rsp, 32					; 00000020H
	mov	rbx, rcx

; 50   : 	if( fdwReason == DLL_PROCESS_ATTACH ) {

	cmp	edx, 1
	jne	SHORT $LN2@DllMain

; 51   : 		MaxSDK::Util::UseLanguagePackLocale();

	lea	rcx, OFFSET FLAT:__ImageBase
	call	QWORD PTR __imp_?UseLanguagePackLocale@Util@MaxSDK@@YAXPEAUHINSTANCE__@@@Z

; 52   : 		hInstance = hinstDLL;
; 53   : 		DisableThreadLibraryCalls(hInstance);

	mov	rcx, rbx
	mov	QWORD PTR ?hInstance@@3PEAUHINSTANCE__@@EA, rbx ; hInstance
	call	QWORD PTR __imp_DisableThreadLibraryCalls
$LN2@DllMain:

; 54   : 	}      
; 55   : 
; 56   : 	if (!controlsInit) {

	cmp	DWORD PTR ?controlsInit@@3HA, 0		; controlsInit
	jne	SHORT $LN5@DllMain

; 57   : 		controlsInit = TRUE;

	mov	DWORD PTR ?controlsInit@@3HA, 1		; controlsInit

; 58   : 		//InitCustomControls(hInstance);     // Initialize MAX's custom controls
; 59   : 		InitCommonControls();              // Initialize Win95 controls

	call	IsolationAwareInitCommonControls

; 60   : 		InitGradientControls();            // Initialize my GradientRamp control

	call	?InitGradientControls@@YAXXZ		; InitGradientControls
$LN5@DllMain:

; 61   : 	}
; 62   : 
; 63   : 	return(TRUE);

	mov	eax, 1

; 64   : }

	add	rsp, 32					; 00000020H
	pop	rbx
	ret	0
DllMain	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtp
; File g:\dropbox\github\berconmaps\src\dllentry.cpp
;	COMDAT ?GetString@@YAPEA_WH@Z
_TEXT	SEGMENT
id$ = 48
?GetString@@YAPEA_WH@Z PROC				; GetString, COMDAT

; 26   : MCHAR *GetString(int id) {

$LN5:
	sub	rsp, 40					; 00000028H
	mov	edx, ecx

; 27   : 	static MCHAR buf[bufsize];
; 28   : 
; 29   : 	if (hInstance)

	mov	rcx, QWORD PTR ?hInstance@@3PEAUHINSTANCE__@@EA ; hInstance
	test	rcx, rcx
	je	SHORT $LN2@GetString

; 30   : 		return LoadString(hInstance, id, buf, sizeof(buf)) ? buf : NULL;

	mov	QWORD PTR [rsp+32], rbx
	mov	r9d, 512				; 00000200H
	lea	rbx, OFFSET FLAT:?buf@?1??GetString@@YAPEA_WH@Z@4PA_WA
	mov	r8, rbx
	call	QWORD PTR __imp_LoadStringW
	xor	ecx, ecx
	test	eax, eax
	cmovne	rcx, rbx
	mov	rbx, QWORD PTR [rsp+32]
	mov	rax, rcx

; 32   : }

	add	rsp, 40					; 00000028H
	ret	0
$LN2@GetString:

; 31   : 	return NULL;

	xor	eax, eax

; 32   : }

	add	rsp, 40					; 00000028H
	ret	0
?GetString@@YAPEA_WH@Z ENDP				; GetString
_TEXT	ENDS
; Function compile flags: /Ogtp
; File c:\program files\autodesk\3ds max 2019 sdk\maxsdk\include\assetmanagement\assetid.h
;	COMDAT ??__EkInvalidId@AssetManagement@MaxSDK@@YAXXZ
text$di	SEGMENT
??__EkInvalidId@AssetManagement@MaxSDK@@YAXXZ PROC	; MaxSDK::AssetManagement::`dynamic initializer for 'kInvalidId'', COMDAT

; 29   : 			AssetId() { *static_cast<GUID*>(this) = CLSID_NULL; }

	vmovups	xmm0, XMMWORD PTR GUID_NULL
	vmovups	XMMWORD PTR ?kInvalidId@AssetManagement@MaxSDK@@3UAssetId@12@A, xmm0

; 32   : 		static AssetId kInvalidId;

	ret	0
??__EkInvalidId@AssetManagement@MaxSDK@@YAXXZ ENDP	; MaxSDK::AssetManagement::`dynamic initializer for 'kInvalidId''
text$di	ENDS
; Function compile flags: /Ogtp
; File c:\program files\autodesk\3ds max 2019 sdk\maxsdk\include\assetmanagement\assetid.h
;	COMDAT ??0AssetId@AssetManagement@MaxSDK@@QEAA@XZ
_TEXT	SEGMENT
this$ = 8
??0AssetId@AssetManagement@MaxSDK@@QEAA@XZ PROC		; MaxSDK::AssetManagement::AssetId::AssetId, COMDAT

; 29   : 			AssetId() { *static_cast<GUID*>(this) = CLSID_NULL; }

	vmovups	xmm0, XMMWORD PTR GUID_NULL
	vmovups	XMMWORD PTR [rcx], xmm0
	mov	rax, rcx
	ret	0
??0AssetId@AssetManagement@MaxSDK@@QEAA@XZ ENDP		; MaxSDK::AssetManagement::AssetId::AssetId
_TEXT	ENDS
; Function compile flags: /Ogtp
; File c:\program files\autodesk\3ds max 2019 sdk\maxsdk\include\maxtypes.h
;	COMDAT ??0Class_ID@@QEAA@KK@Z
_TEXT	SEGMENT
this$ = 8
aa$ = 16
bb$ = 24
??0Class_ID@@QEAA@KK@Z PROC				; Class_ID::Class_ID, COMDAT

; 160  : 	Class_ID(ulong aa, ulong bb) { a = aa; b = bb; }

	mov	DWORD PTR [rcx], edx
	mov	rax, rcx
	mov	DWORD PTR [rcx+4], r8d
	ret	0
??0Class_ID@@QEAA@KK@Z ENDP				; Class_ID::Class_ID
_TEXT	ENDS
; Function compile flags: /Ogtp
; File c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\commctrl.inl
; File c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\winbase.inl
; File c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\commctrl.inl
; File c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\winbase.inl
; File c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\commctrl.inl
;	COMDAT IsolationAwareInitCommonControls
_TEXT	SEGMENT
ulpCookie$ = 48
IsolationAwareInitCommonControls PROC			; COMDAT

; 239  : {

$LN39:
	push	rbx
	sub	rsp, 32					; 00000020H

; 240  :     typedef void (WINAPI* PFN)(void);
; 241  :     static PFN s_pfn;
; 242  :     PFN __IsolationAware_pfn = s_pfn;

	mov	rbx, QWORD PTR ?s_pfn@?1??IsolationAwareInitCommonControls@@9@4P6AXXZEA ; `IsolationAwareInitCommonControls'::`2'::s_pfn

; 243  :     ULONG_PTR ulpCookie = 0;

	mov	QWORD PTR ulpCookie$[rsp], 0

; 244  :     const BOOL fActivateActCtxSuccess =
; 245  :         IsolationAwarePrivateT_SAbnPgpgk ||
; 246  :         IsolationAwarePrivateT_SqbjaYRiRY ||

	cmp	DWORD PTR IsolationAwarePrivateT_SAbnPgpgk, 0
	jne	SHORT $LN9@IsolationA
	mov	eax, DWORD PTR IsolationAwarePrivateT_SqbjaYRiRY
	test	eax, eax
	jne	SHORT $LN9@IsolationA
; File c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\winbase.inl

; 585  :     if (WinbaseIsolationAwarePrivateT_SpYRNahcpNYYRQ)

	mov	ecx, DWORD PTR WinbaseIsolationAwarePrivateT_SpYRNahcpNYYRQ
	test	ecx, ecx
	je	SHORT $LN19@IsolationA

; 586  :     {
; 587  :         const static char debugString[] = "IsolationAware function called after IsolationAwareCleanup\n";
; 588  :         OutputDebugStringA(debugString);

	lea	rcx, OFFSET FLAT:?debugString@?4??IsolationAwarePrivatenPgViNgRzlnPgpgk@@9@4QBDB ; `IsolationAwarePrivatenPgViNgRzlnPgpgk'::`5'::debugString
	call	QWORD PTR __imp_OutputDebugStringA
	mov	eax, DWORD PTR IsolationAwarePrivateT_SqbjaYRiRY
	mov	ecx, DWORD PTR WinbaseIsolationAwarePrivateT_SpYRNahcpNYYRQ
$LN19@IsolationA:

; 589  :     }
; 590  : 
; 591  :     if (IsolationAwarePrivateT_SqbjaYRiRY)

	test	eax, eax
	jne	SHORT $LN9@IsolationA

; 592  :     {
; 593  :         fResult = TRUE;
; 594  :         goto Exit;
; 595  :     }
; 596  : 
; 597  :     /* Do not call Init if Cleanup has been called. */
; 598  :     if (!WinbaseIsolationAwarePrivateT_SpYRNahcpNYYRQ)

	test	ecx, ecx
	jne	SHORT $LN23@IsolationA

; 599  :     {
; 600  :         if (!WinbaseIsolationAwarePrivatetRgzlnPgpgk())

	call	WinbaseIsolationAwarePrivatetRgzlnPgpgk
	test	eax, eax
	je	SHORT $Exit$40
$LN23@IsolationA:

; 146  :     return ActivateActCtx(hActCtx,lpCookie);

	lea	rdx, QWORD PTR ulpCookie$[rsp]
	mov	rcx, QWORD PTR WinbaseIsolationAwarePrivateT_UnPgpgk
	call	QWORD PTR __imp_ActivateActCtx

; 604  :     if (!IsolationAwareActivateActCtx(WinbaseIsolationAwarePrivateT_UnPgpgk, pulpCookie))

	test	eax, eax
	jne	SHORT $LN9@IsolationA
$Exit$40:

; 605  :         goto Exit;
; 606  : 
; 607  :     fResult = TRUE;
; 608  : Exit:
; 609  :     if (!fResult)
; 610  :     {
; 611  :         const DWORD dwLastError = GetLastError();

	call	QWORD PTR __imp_GetLastError
	lea	ecx, DWORD PTR [rax-126]
	cmp	ecx, 1
	jbe	SHORT $LN29@IsolationA
	cmp	eax, 120				; 00000078H
	je	SHORT $LN29@IsolationA
	cmp	eax, 1
	je	SHORT $LN29@IsolationA
	cmp	eax, 50					; 00000032H
	jne	SHORT $LN12@IsolationA
$LN29@IsolationA:

; 612  :         if (dwLastError == ERROR_PROC_NOT_FOUND
; 613  :             || dwLastError == ERROR_MOD_NOT_FOUND
; 614  :             || dwLastError == ERROR_CALL_NOT_IMPLEMENTED
; 615  :             || dwLastError == ERROR_INVALID_FUNCTION
; 616  :             || dwLastError == ERROR_NOT_SUPPORTED)
; 617  :         {
; 618  :             IsolationAwarePrivateT_SqbjaYRiRY = TRUE;

	mov	DWORD PTR IsolationAwarePrivateT_SqbjaYRiRY, 1
$LN9@IsolationA:
; File c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\commctrl.inl

; 252  :         if (__IsolationAware_pfn == NULL)

	test	rbx, rbx
	jne	SHORT $LN4@IsolationA

; 253  :         {
; 254  :             __IsolationAware_pfn = (PFN) CommctrlIsolationAwarePrivatetRgCebPnQQeRff_pbZPgYQP_QYY("InitCommonControls");

	lea	rcx, OFFSET FLAT:??_C@_0BD@KDNHKDOA@InitCommonControls?$AA@
	call	CommctrlIsolationAwarePrivatetRgCebPnQQeRff_pbZPgYQP_QYY
	mov	rbx, rax

; 255  :             if (__IsolationAware_pfn == NULL)

	test	rax, rax
	je	SHORT $LN3@IsolationA

; 256  :                 __leave;
; 257  :             s_pfn = __IsolationAware_pfn;

	mov	QWORD PTR ?s_pfn@?1??IsolationAwareInitCommonControls@@9@4P6AXXZEA, rax ; `IsolationAwareInitCommonControls'::`2'::s_pfn
$LN4@IsolationA:

; 258  :         }
; 259  :         __IsolationAware_pfn();

	call	rbx
	npad	1
$LN3@IsolationA:
$LN17@IsolationA:

; 260  :     }
; 261  :     __finally
; 262  :     {
; 263  :         if (!IsolationAwarePrivateT_SAbnPgpgk
; 264  :          || !IsolationAwarePrivateT_SqbjaYRiRY

	cmp	DWORD PTR IsolationAwarePrivateT_SAbnPgpgk, 0
	je	SHORT $LN11@IsolationA
	cmp	DWORD PTR IsolationAwarePrivateT_SqbjaYRiRY, 0
	jne	SHORT $LN12@IsolationA
$LN11@IsolationA:
; File c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\winbase.inl

; 167  :     return DeactivateActCtx(dwFlags,ulCookie);

	mov	rdx, QWORD PTR ulpCookie$[rsp]
	xor	ecx, ecx
	call	QWORD PTR __imp_DeactivateActCtx
$LN12@IsolationA:
; File c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\commctrl.inl

; 271  : }

	add	rsp, 32					; 00000020H
	pop	rbx
	ret	0
IsolationAwareInitCommonControls ENDP
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
ulpCookie$ = 48
IsolationAwareInitCommonControls$fin$0 PROC

; 260  :     }

	push	rbp
	sub	rsp, 32					; 00000020H
	mov	rbp, rdx
$LN14@IsolationA:

; 260  :     }
; 261  :     __finally
; 262  :     {
; 263  :         if (!IsolationAwarePrivateT_SAbnPgpgk
; 264  :          || !IsolationAwarePrivateT_SqbjaYRiRY

	cmp	DWORD PTR IsolationAwarePrivateT_SAbnPgpgk, 0
	je	SHORT $LN7@IsolationA
	cmp	DWORD PTR IsolationAwarePrivateT_SqbjaYRiRY, 0
	jne	SHORT $LN15@IsolationA
$LN7@IsolationA:
; File c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\winbase.inl

; 167  :     return DeactivateActCtx(dwFlags,ulCookie);

	mov	rdx, QWORD PTR ulpCookie$[rbp]
	xor	ecx, ecx
	call	QWORD PTR __imp_DeactivateActCtx
	npad	1
$LN15@IsolationA:
	add	rsp, 32					; 00000020H
	pop	rbp
	ret	0
	int	3
IsolationAwareInitCommonControls$fin$0 ENDP
text$x	ENDS
; Function compile flags: /Ogtp
; File c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\commctrl.inl
; File c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\winbase.inl
;	COMDAT text$x
text$x	SEGMENT
ulpCookie$ = 48
IsolationAwareInitCommonControls$fin$0 PROC
; File c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\commctrl.inl

; 260  :     }

	push	rbp
	sub	rsp, 32					; 00000020H
	mov	rbp, rdx
$LN14@IsolationA:

; 261  :     __finally
; 262  :     {
; 263  :         if (!IsolationAwarePrivateT_SAbnPgpgk
; 264  :          || !IsolationAwarePrivateT_SqbjaYRiRY

	cmp	DWORD PTR IsolationAwarePrivateT_SAbnPgpgk, 0
	je	SHORT $LN7@IsolationA
	cmp	DWORD PTR IsolationAwarePrivateT_SqbjaYRiRY, 0
	jne	SHORT $LN15@IsolationA
$LN7@IsolationA:
; File c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\winbase.inl

; 167  :     return DeactivateActCtx(dwFlags,ulCookie);

	mov	rdx, QWORD PTR ulpCookie$[rbp]
	xor	ecx, ecx
	call	QWORD PTR __imp_DeactivateActCtx
	npad	1
$LN15@IsolationA:
	add	rsp, 32					; 00000020H
	pop	rbp
	ret	0
	int	3
IsolationAwareInitCommonControls$fin$0 ENDP
text$x	ENDS
; Function compile flags: /Ogtp
; File c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\commctrl.inl
; File c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\winbase.inl
; File c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\commctrl.inl
; File c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\winbase.inl
; File c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\commctrl.inl
;	COMDAT CommctrlIsolationAwarePrivatetRgCebPnQQeRff_pbZPgYQP_QYY
_TEXT	SEGMENT
fActivateActCtxSuccess$ = 32
proc$ = 40
pszProcName$ = 64
ulpCookie$ = 72
CommctrlIsolationAwarePrivatetRgCebPnQQeRff_pbZPgYQP_QYY PROC ; COMDAT

; 4383 : {

$LN28:
	mov	rax, rsp
	mov	QWORD PTR [rax+8], rbx
	mov	QWORD PTR [rax+24], rsi
	mov	QWORD PTR [rax+32], rdi
	push	r14
	sub	rsp, 48					; 00000030H
	mov	r14, rcx

; 4384 :     FARPROC proc = NULL;

	xor	edi, edi
	mov	ebx, edi
	mov	QWORD PTR [rax-16], rbx

; 4385 :     static HMODULE s_module;
; 4386 :     BOOL fActivateActCtxSuccess = FALSE;

	mov	esi, edi
	mov	DWORD PTR [rax-24], edi

; 4387 :     ULONG_PTR ulpCookie = 0;

	mov	QWORD PTR [rax+16], rdi

; 4388 : #ifndef _M_CEE_PURE
; 4389 :     const static IsolationAwarePrivatepBAFGnAG_zBqHyr_vAsB
; 4390 :         c = { IsolationAwarePrivatezlybNQyVOeNelJ, L"Comctl32.dll"
; 4391 : #ifdef _M_IX86
; 4392 :              , IsolationAwarePrivatezlybNQyVOeNeln, "Comctl32.dll"
; 4393 : #endif
; 4394 :     };
; 4395 : #else
; 4396 :     static IsolationAwarePrivatepBAFGnAG_zBqHyr_vAsB c;
; 4397 :     c.WinbaseIsolationAwarePrivateybNQJ = IsolationAwarePrivatezlybNQyVOeNelJ;
; 4398 :     c.WinbaseIsolationAwarePrivateANZRJ = L"Comctl32.dll";
; 4399 : #ifdef _M_IX86
; 4400 :     c.WinbaseIsolationAwarePrivateybNQn = IsolationAwarePrivatezlybNQyVOeNeln;
; 4401 :     c.WinbaseIsolationAwarePrivateANZRn = "Comctl32.dll";
; 4402 : #endif
; 4403 : #endif
; 4404 :     static IsolationAwarePrivatezHGnoyr_zBqHyr_vAsB m;
; 4405 : 
; 4406 :     __try
; 4407 :     {
; 4408 :         if (!IsolationAwarePrivateT_SqbjaYRiRY)

	cmp	DWORD PTR IsolationAwarePrivateT_SqbjaYRiRY, edi
	jne	SHORT $LN4@CommctrlIs

; 4409 :         {
; 4410 :             fActivateActCtxSuccess = IsolationAwarePrivatenPgViNgRzlnPgpgk(&ulpCookie);

	lea	rcx, QWORD PTR [rax+16]
	call	IsolationAwarePrivatenPgViNgRzlnPgpgk
	mov	esi, eax
	mov	DWORD PTR fActivateActCtxSuccess$[rsp], eax

; 4411 :             if (!fActivateActCtxSuccess)

	test	eax, eax
	je	SHORT $LN2@CommctrlIs
$LN4@CommctrlIs:
; File c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\winbase.inl

; 372  :     FARPROC Proc = NULL;

	mov	rbx, rdi

; 373  :     HMODULE hModule;
; 374  :     hModule = m->WinbaseIsolationAwarePrivateybNQRQzbQhYR;

	mov	rax, QWORD PTR ?m@?1??CommctrlIsolationAwarePrivatetRgCebPnQQeRff_pbZPgYQP_QYY@@9@4UIsolationAwarePrivate_zHGnoyr_zBqHyr_vAsB@@A ; `CommctrlIsolationAwarePrivatetRgCebPnQQeRff_pbZPgYQP_QYY'::`2'::m

; 375  :     if (hModule == NULL)

	test	rax, rax
	jne	SHORT $LN20@CommctrlIs

; 376  :     {
; 377  :         hModule = (*c->WinbaseIsolationAwarePrivateybNQJ)(c->WinbaseIsolationAwarePrivateANZRJ);

	mov	rcx, QWORD PTR ?c@?1??CommctrlIsolationAwarePrivatetRgCebPnQQeRff_pbZPgYQP_QYY@@9@4UIsolationAwarePrivate_pBAFGnAG_zBqHyr_vAsB@@B+8
	call	IsolationAwarePrivatezlybNQyVOeNelJ

; 378  :         if (hModule == NULL)

	test	rax, rax
	je	SHORT $Exit$29

; 379  :             goto Exit;
; 380  :         m->WinbaseIsolationAwarePrivateybNQRQzbQhYR = hModule;

	mov	QWORD PTR ?m@?1??CommctrlIsolationAwarePrivatetRgCebPnQQeRff_pbZPgYQP_QYY@@9@4UIsolationAwarePrivate_zHGnoyr_zBqHyr_vAsB@@A, rax ; `CommctrlIsolationAwarePrivatetRgCebPnQQeRff_pbZPgYQP_QYY'::`2'::m
$LN20@CommctrlIs:

; 381  :     }
; 382  :     Proc = GetProcAddress(hModule, ProcName);

	mov	rdx, r14
	mov	rcx, rax
	call	QWORD PTR __imp_GetProcAddress
	mov	rbx, rax
$Exit$29:
; File c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\commctrl.inl

; 4414 :         proc = IsolationAwarePrivatezltRgCebPnQQeRff(&c, &m, pszProcName);

	mov	QWORD PTR proc$[rsp], rbx
$LN2@CommctrlIs:
$LN18@CommctrlIs:

; 4415 :     }
; 4416 :     __finally
; 4417 :     {
; 4418 :         if (
; 4419 :             !IsolationAwarePrivateT_SqbjaYRiRY &&

	cmp	DWORD PTR IsolationAwarePrivateT_SqbjaYRiRY, 0
	jne	SHORT $LN12@CommctrlIs
	test	esi, esi
	je	SHORT $LN12@CommctrlIs

; 4420 :             fActivateActCtxSuccess)
; 4421 :         {
; 4422 :             const DWORD dwLastError = (proc == NULL) ? GetLastError() : NO_ERROR;

	test	rbx, rbx
	jne	SHORT $LN11@CommctrlIs
	call	QWORD PTR __imp_GetLastError
	mov	edi, eax
$LN11@CommctrlIs:
; File c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\winbase.inl

; 167  :     return DeactivateActCtx(dwFlags,ulCookie);

	mov	rdx, QWORD PTR ulpCookie$[rsp]
	xor	ecx, ecx
	call	QWORD PTR __imp_DeactivateActCtx
; File c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\commctrl.inl

; 4424 :             if (proc == NULL)

	test	rbx, rbx
	jne	SHORT $LN12@CommctrlIs

; 4425 :                 SetLastError(dwLastError);

	mov	ecx, edi
	call	QWORD PTR __imp_SetLastError
$LN12@CommctrlIs:

; 4426 :         }
; 4427 :     }
; 4428 :     return proc;

	mov	rax, rbx
$LN14@CommctrlIs:

; 4429 : }

	mov	rbx, QWORD PTR [rsp+64]
	mov	rsi, QWORD PTR [rsp+80]
	mov	rdi, QWORD PTR [rsp+88]
	add	rsp, 48					; 00000030H
	pop	r14
	ret	0
CommctrlIsolationAwarePrivatetRgCebPnQQeRff_pbZPgYQP_QYY ENDP
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
fActivateActCtxSuccess$ = 32
proc$ = 40
pszProcName$ = 64
ulpCookie$ = 72
CommctrlIsolationAwarePrivatetRgCebPnQQeRff_pbZPgYQP_QYY$fin$0 PROC

; 4415 :     }

	push	rbx
	push	rbp
	push	rdi
	sub	rsp, 32					; 00000020H
	mov	rbp, rdx
$LN15@CommctrlIs:

; 4415 :     }
; 4416 :     __finally
; 4417 :     {
; 4418 :         if (
; 4419 :             !IsolationAwarePrivateT_SqbjaYRiRY &&

	cmp	DWORD PTR IsolationAwarePrivateT_SqbjaYRiRY, 0
	jne	SHORT $LN16@CommctrlIs
	cmp	DWORD PTR fActivateActCtxSuccess$[rbp], 0
	je	SHORT $LN16@CommctrlIs

; 4420 :             fActivateActCtxSuccess)
; 4421 :         {
; 4422 :             const DWORD dwLastError = (proc == NULL) ? GetLastError() : NO_ERROR;

	mov	rbx, QWORD PTR proc$[rbp]
	test	rbx, rbx
	jne	SHORT $LN8@CommctrlIs
	call	QWORD PTR __imp_GetLastError
	mov	edi, eax
	jmp	SHORT $LN9@CommctrlIs
$LN8@CommctrlIs:
	xor	edi, edi
$LN9@CommctrlIs:
; File c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\winbase.inl

; 167  :     return DeactivateActCtx(dwFlags,ulCookie);

	mov	rdx, QWORD PTR ulpCookie$[rbp]
	xor	ecx, ecx
	call	QWORD PTR __imp_DeactivateActCtx
; File c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\commctrl.inl

; 4424 :             if (proc == NULL)

	test	rbx, rbx
	jne	SHORT $LN16@CommctrlIs

; 4425 :                 SetLastError(dwLastError);

	mov	ecx, edi
	call	QWORD PTR __imp_SetLastError
	npad	1
$LN16@CommctrlIs:
	add	rsp, 32					; 00000020H
	pop	rdi
	pop	rbp
	pop	rbx
	ret	0
	int	3
CommctrlIsolationAwarePrivatetRgCebPnQQeRff_pbZPgYQP_QYY$fin$0 ENDP
text$x	ENDS
; Function compile flags: /Ogtp
; File c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\winbase.inl
; File c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\commctrl.inl
;	COMDAT text$x
text$x	SEGMENT
fActivateActCtxSuccess$ = 32
proc$ = 40
pszProcName$ = 64
ulpCookie$ = 72
CommctrlIsolationAwarePrivatetRgCebPnQQeRff_pbZPgYQP_QYY$fin$0 PROC

; 4415 :     }

	push	rbx
	push	rbp
	push	rdi
	sub	rsp, 32					; 00000020H
	mov	rbp, rdx
$LN15@CommctrlIs:

; 4416 :     __finally
; 4417 :     {
; 4418 :         if (
; 4419 :             !IsolationAwarePrivateT_SqbjaYRiRY &&

	cmp	DWORD PTR IsolationAwarePrivateT_SqbjaYRiRY, 0
	jne	SHORT $LN16@CommctrlIs
	cmp	DWORD PTR fActivateActCtxSuccess$[rbp], 0
	je	SHORT $LN16@CommctrlIs

; 4420 :             fActivateActCtxSuccess)
; 4421 :         {
; 4422 :             const DWORD dwLastError = (proc == NULL) ? GetLastError() : NO_ERROR;

	mov	rbx, QWORD PTR proc$[rbp]
	test	rbx, rbx
	jne	SHORT $LN8@CommctrlIs
	call	QWORD PTR __imp_GetLastError
	mov	edi, eax
	jmp	SHORT $LN9@CommctrlIs
$LN8@CommctrlIs:
	xor	edi, edi
$LN9@CommctrlIs:
; File c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\winbase.inl

; 167  :     return DeactivateActCtx(dwFlags,ulCookie);

	mov	rdx, QWORD PTR ulpCookie$[rbp]
	xor	ecx, ecx
	call	QWORD PTR __imp_DeactivateActCtx
; File c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\commctrl.inl

; 4424 :             if (proc == NULL)

	test	rbx, rbx
	jne	SHORT $LN16@CommctrlIs

; 4425 :                 SetLastError(dwLastError);

	mov	ecx, edi
	call	QWORD PTR __imp_SetLastError
	npad	1
$LN16@CommctrlIs:
	add	rsp, 32					; 00000020H
	pop	rdi
	pop	rbp
	pop	rbx
	ret	0
	int	3
CommctrlIsolationAwarePrivatetRgCebPnQQeRff_pbZPgYQP_QYY$fin$0 ENDP
text$x	ENDS
; Function compile flags: /Ogtp
; File c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\winbase.inl
;	COMDAT WinbaseIsolationAwarePrivatetRgzlnPgpgk
_TEXT	SEGMENT
actCtxBasicInfo$ = 64
actCtxSectionKeyedData$1 = 80
actCtx$2 = 80
rgchFullModulePath$3 = 192
ulpCookie$ = 736
hmodSelf$4 = 744
WinbaseIsolationAwarePrivatetRgzlnPgpgk PROC		; COMDAT

; 396  : {

$LN40:
	push	rbx
	sub	rsp, 720				; 000002d0H

; 397  :     BOOL fResult = FALSE;

	xor	ebx, ebx

; 398  :     ACTIVATION_CONTEXT_BASIC_INFORMATION actCtxBasicInfo;
; 399  :     ULONG_PTR ulpCookie = 0;

	mov	QWORD PTR ulpCookie$[rsp], rbx

; 400  : 
; 401  :     if (IsolationAwarePrivateT_SqbjaYRiRY)

	cmp	DWORD PTR IsolationAwarePrivateT_SqbjaYRiRY, ebx
	jne	$LN18@WinbaseIso

; 402  :     {
; 403  :         fResult = TRUE;
; 404  :         goto Exit;
; 405  :     }
; 406  : 
; 407  :     if (WinbaseIsolationAwarePrivateT_UnPgpgk != INVALID_HANDLE_VALUE)

	cmp	QWORD PTR WinbaseIsolationAwarePrivateT_UnPgpgk, -1
	jne	$LN18@WinbaseIso

; 209  :     return QueryActCtxW(dwFlags,hActCtx,pvSubInstance,ulInfoClass,pvBuffer,cbBuffer,pcbWrittenOrRequired);

	mov	QWORD PTR [rsp+48], rbx
	mov	QWORD PTR [rsp+40], 16
	lea	rax, QWORD PTR actCtxBasicInfo$[rsp]
	mov	QWORD PTR [rsp+32], rax
	lea	r9d, QWORD PTR [rbx+1]
	xor	r8d, r8d
	lea	rdx, OFFSET FLAT:WinbaseIsolationAwarePrivateT_UnPgpgk
	mov	ecx, -2147483632			; 80000010H
	call	QWORD PTR __imp_QueryActCtxW

; 408  :     {
; 409  :         fResult = TRUE;
; 410  :         goto Exit;
; 411  :     }
; 412  : 
; 413  :     if (!IsolationAwareQueryActCtxW(

	test	eax, eax
	je	$Exit$41

; 414  :         QUERY_ACTCTX_FLAG_ACTCTX_IS_ADDRESS
; 415  :         | QUERY_ACTCTX_FLAG_NO_ADDREF,
; 416  :         &WinbaseIsolationAwarePrivateT_UnPgpgk,
; 417  :         NULL,
; 418  :         ActivationContextBasicInformation,
; 419  :         &actCtxBasicInfo,
; 420  :         sizeof(actCtxBasicInfo),
; 421  :         NULL))
; 422  :         goto Exit;
; 423  : 
; 424  :     /*
; 425  :     If QueryActCtxW returns NULL, try CreateActCtx(3).
; 426  :     */
; 427  :     if (actCtxBasicInfo.hActCtx == NULL)

	mov	rax, QWORD PTR actCtxBasicInfo$[rsp]
	test	rax, rax
	jne	$LN8@WinbaseIso

; 428  :     {
; 429  :         ACTCTXW actCtx;
; 430  :         WCHAR rgchFullModulePath[MAX_PATH + 1];
; 431  :         DWORD dw;
; 432  :         HMODULE hmodSelf;
; 433  : #ifdef _M_IX86
; 434  :         PGET_MODULE_HANDLE_EXW pfnGetModuleHandleExW = (PGET_MODULE_HANDLE_EXW)WinbaseIsolationAwarePrivatetRgCebPnQQeRff_xReaRYQP_QYY("GetModuleHandleExW");
; 435  :         if (pfnGetModuleHandleExW == NULL)
; 436  :             goto Exit;
; 437  : #endif
; 438  :         if (!

	lea	r8, QWORD PTR hmodSelf$4[rsp]
	lea	rdx, OFFSET FLAT:WinbaseIsolationAwarePrivateT_UnPgpgk
	lea	ecx, QWORD PTR [rbx+6]
	call	QWORD PTR __imp_GetModuleHandleExW
	test	eax, eax
	je	$Exit$41

; 439  : #ifdef _M_IX86
; 440  :             (*pfnGetModuleHandleExW)
; 441  : #else
; 442  :             GetModuleHandleExW
; 443  : #endif
; 444  :             (     GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT
; 445  :                 | GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS,
; 446  :                 (LPCWSTR)&WinbaseIsolationAwarePrivateT_UnPgpgk,
; 447  :                 &hmodSelf))
; 448  :             goto Exit;
; 449  : 
; 450  :         dw = GetModuleFileNameW(hmodSelf, rgchFullModulePath, WINBASE_NUMBER_OF(rgchFullModulePath));

	mov	r8d, 261				; 00000105H
	lea	rdx, QWORD PTR rgchFullModulePath$3[rsp]
	mov	rcx, QWORD PTR hmodSelf$4[rsp]
	call	QWORD PTR __imp_GetModuleFileNameW

; 451  :         if (dw == 0)

	test	eax, eax
	je	$Exit$41

; 452  :             goto Exit;
; 453  :         if (dw >= WINBASE_NUMBER_OF(rgchFullModulePath))

	cmp	eax, 261				; 00000105H
	jb	SHORT $LN13@WinbaseIso

; 454  :         {
; 455  :             SetLastError(ERROR_BUFFER_OVERFLOW);

	lea	ecx, QWORD PTR [rbx+111]
	call	QWORD PTR __imp_SetLastError

; 456  :             goto Exit;

	jmp	$Exit$41
$LN13@WinbaseIso:

; 457  :         }
; 458  : 
; 459  :         actCtx.cbSize = sizeof(actCtx);

	mov	DWORD PTR actCtx$2[rsp], 56		; 00000038H

; 460  :         actCtx.dwFlags = ACTCTX_FLAG_RESOURCE_NAME_VALID | ACTCTX_FLAG_HMODULE_VALID;

	mov	DWORD PTR actCtx$2[rsp+4], 136		; 00000088H

; 461  :         actCtx.lpSource = rgchFullModulePath;

	lea	rax, QWORD PTR rgchFullModulePath$3[rsp]
	mov	QWORD PTR actCtx$2[rsp+8], rax

; 462  :         actCtx.lpResourceName = (LPCWSTR)(ULONG_PTR)3;

	mov	QWORD PTR actCtx$2[rsp+32], 3

; 463  :         actCtx.hModule = hmodSelf;

	mov	rax, QWORD PTR hmodSelf$4[rsp]
	mov	QWORD PTR actCtx$2[rsp+48], rax

; 105  :     return CreateActCtxW(pActCtx);

	lea	rcx, QWORD PTR actCtx$2[rsp]
	call	QWORD PTR __imp_CreateActCtxW
	mov	QWORD PTR actCtxBasicInfo$[rsp], rax

; 464  :         actCtxBasicInfo.hActCtx = IsolationAwareCreateActCtxW(&actCtx);
; 465  :         if (actCtxBasicInfo.hActCtx == INVALID_HANDLE_VALUE)

	cmp	rax, -1
	jne	SHORT $LN15@WinbaseIso

; 466  :         {
; 467  :             const DWORD dwLastError = GetLastError();

	call	QWORD PTR __imp_GetLastError
	lea	ecx, DWORD PTR [rax-1812]
	cmp	ecx, 3
	jbe	SHORT $LN16@WinbaseIso
	add	eax, -2					; fffffffeH
	cmp	eax, 1
	ja	SHORT $Exit$41
$LN16@WinbaseIso:

; 468  :             if ((dwLastError != ERROR_RESOURCE_DATA_NOT_FOUND) &&
; 469  :                 (dwLastError != ERROR_RESOURCE_TYPE_NOT_FOUND) &&
; 470  :                 (dwLastError != ERROR_RESOURCE_LANG_NOT_FOUND) &&
; 471  :                 (dwLastError != ERROR_RESOURCE_NAME_NOT_FOUND) &&
; 472  :                 (dwLastError != ERROR_FILE_NOT_FOUND) &&
; 473  :                 (dwLastError != ERROR_PATH_NOT_FOUND))
; 474  :                 goto Exit;
; 475  : 
; 476  :             actCtxBasicInfo.hActCtx = NULL;

	mov	rax, rbx
	mov	QWORD PTR actCtxBasicInfo$[rsp], rbx
$LN15@WinbaseIso:

; 477  :         }
; 478  : 
; 479  :         WinbaseIsolationAwarePrivateT_SpeRNgRQnPgpgk = TRUE;

	mov	DWORD PTR WinbaseIsolationAwarePrivateT_SpeRNgRQnPgpgk, 1
$LN8@WinbaseIso:

; 480  :     }
; 481  : 
; 482  :     WinbaseIsolationAwarePrivateT_UnPgpgk = actCtxBasicInfo.hActCtx;

	mov	QWORD PTR WinbaseIsolationAwarePrivateT_UnPgpgk, rax

; 146  :     return ActivateActCtx(hActCtx,lpCookie);

	lea	rdx, QWORD PTR ulpCookie$[rsp]
	mov	rcx, rax
	call	QWORD PTR __imp_ActivateActCtx

; 483  : 
; 484  : #define ACTIVATION_CONTEXT_SECTION_DLL_REDIRECTION              (2)
; 485  : 
; 486  :     if (IsolationAwareActivateActCtx(actCtxBasicInfo.hActCtx, &ulpCookie))

	test	eax, eax
	je	SHORT $LN18@WinbaseIso

; 487  :     {
; 488  :         __try
; 489  :         {
; 490  :             ACTCTX_SECTION_KEYED_DATA actCtxSectionKeyedData;
; 491  : 
; 492  :             actCtxSectionKeyedData.cbSize = sizeof(actCtxSectionKeyedData);

	mov	DWORD PTR actCtxSectionKeyedData$1[rsp], 112 ; 00000070H

; 188  :     return FindActCtxSectionStringW(dwFlags,lpExtensionGuid,ulSectionId,lpStringToFind,ReturnedData);

	lea	rax, QWORD PTR actCtxSectionKeyedData$1[rsp]
	mov	QWORD PTR [rsp+32], rax
	lea	r9, OFFSET FLAT:??_C@_1BK@BFMCNHEO@?$AAC?$AAo?$AAm?$AAc?$AAt?$AAl?$AA3?$AA2?$AA?4?$AAd?$AAl?$AAl?$AA?$AA@
	xor	edx, edx
	xor	ecx, ecx
	lea	r8d, QWORD PTR [rdx+2]
	call	QWORD PTR __imp_FindActCtxSectionStringW

; 493  :             if (IsolationAwareFindActCtxSectionStringW(0, NULL, ACTIVATION_CONTEXT_SECTION_DLL_REDIRECTION, L"Comctl32.dll", &actCtxSectionKeyedData))

	test	eax, eax
	je	SHORT $LN20@WinbaseIso

; 494  :             {
; 495  :                 /* get button, edit, etc. registered */
; 496  :                 LoadLibraryW(L"Comctl32.dll");

	lea	rcx, OFFSET FLAT:??_C@_1BK@BFMCNHEO@?$AAC?$AAo?$AAm?$AAc?$AAt?$AAl?$AA3?$AA2?$AA?4?$AAd?$AAl?$AAl?$AA?$AA@
	call	QWORD PTR __imp_LoadLibraryW
	npad	1
$LN20@WinbaseIso:
$LN26@WinbaseIso:

; 167  :     return DeactivateActCtx(dwFlags,ulCookie);

	mov	rdx, QWORD PTR ulpCookie$[rsp]
	xor	ecx, ecx
	call	QWORD PTR __imp_DeactivateActCtx
$LN18@WinbaseIso:

; 497  :             }
; 498  :         }
; 499  :         __finally
; 500  :         {
; 501  :             IsolationAwareDeactivateActCtx(0, ulpCookie);
; 502  :         }
; 503  :     }
; 504  : 
; 505  :     fResult = TRUE;

	mov	ebx, 1
$Exit$41:

; 506  : Exit:
; 507  :     return fResult;

	mov	eax, ebx
$LN22@WinbaseIso:

; 508  : }

	add	rsp, 720				; 000002d0H
	pop	rbx
	ret	0
WinbaseIsolationAwarePrivatetRgzlnPgpgk ENDP
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
actCtxBasicInfo$ = 64
actCtxSectionKeyedData$1 = 80
actCtx$2 = 80
rgchFullModulePath$3 = 192
ulpCookie$ = 736
hmodSelf$4 = 744
WinbaseIsolationAwarePrivatetRgzlnPgpgk$fin$0 PROC

; 497  :             }
; 498  :         }

	push	rbp
	sub	rsp, 64					; 00000040H
	mov	rbp, rdx
$LN23@WinbaseIso:

; 167  :     return DeactivateActCtx(dwFlags,ulCookie);

	mov	rdx, QWORD PTR ulpCookie$[rbp]
	xor	ecx, ecx
	call	QWORD PTR __imp_DeactivateActCtx
	npad	1
$LN24@WinbaseIso:
	add	rsp, 64					; 00000040H
	pop	rbp
	ret	0
	int	3
WinbaseIsolationAwarePrivatetRgzlnPgpgk$fin$0 ENDP
text$x	ENDS
; Function compile flags: /Ogtp
;	COMDAT text$x
text$x	SEGMENT
actCtxBasicInfo$ = 64
actCtxSectionKeyedData$1 = 80
actCtx$2 = 80
rgchFullModulePath$3 = 192
ulpCookie$ = 736
hmodSelf$4 = 744
WinbaseIsolationAwarePrivatetRgzlnPgpgk$fin$0 PROC

; 168  : #else
; 169  :     BOOL fResult = FALSE;
; 170  :     typedef BOOL (WINAPI* PFN)(_In_ DWORD dwFlags,_In_ ULONG_PTR ulCookie);
; 171  :     static PFN s_pfn;
; 172  :     PFN __IsolationAware_pfn = s_pfn;
; 173  :     if (__IsolationAware_pfn == NULL)
; 174  :     {
; 175  :         __IsolationAware_pfn = (PFN) WinbaseIsolationAwarePrivatetRgCebPnQQeRff_xReaRYQP_QYY("DeactivateActCtx");
; 176  :         if (__IsolationAware_pfn == NULL)
; 177  :             return fResult;
; 178  :         s_pfn = __IsolationAware_pfn;
; 179  :     }
; 180  :     fResult = __IsolationAware_pfn(dwFlags,ulCookie);
; 181  :     return fResult;
; 182  : #endif
; 183  : }
; 184  : 
; 185  : _Success_(return) ISOLATION_AWARE_INLINE BOOL IsolationAwarePrivatenCv IsolationAwareFindActCtxSectionStringW(_In_ DWORD dwFlags,_Reserved_ const GUID*lpExtensionGuid,_In_ ULONG ulSectionId,_In_ LPCWSTR lpStringToFind,_Out_ PACTCTX_SECTION_KEYED_DATA ReturnedData)
; 186  : {
; 187  : #ifdef _WIN64
; 188  :     return FindActCtxSectionStringW(dwFlags,lpExtensionGuid,ulSectionId,lpStringToFind,ReturnedData);
; 189  : #else
; 190  :     BOOL fResult = FALSE;
; 191  :     typedef BOOL (WINAPI* PFN)(_In_ DWORD dwFlags,_Reserved_ const GUID*lpExtensionGuid,_In_ ULONG ulSectionId,_In_ LPCWSTR lpStringToFind,_Out_ PACTCTX_SECTION_KEYED_DATA ReturnedData);
; 192  :     static PFN s_pfn;
; 193  :     PFN __IsolationAware_pfn = s_pfn;
; 194  :     if (__IsolationAware_pfn == NULL)
; 195  :     {
; 196  :         __IsolationAware_pfn = (PFN) WinbaseIsolationAwarePrivatetRgCebPnQQeRff_xReaRYQP_QYY("FindActCtxSectionStringW");
; 197  :         if (__IsolationAware_pfn == NULL)
; 198  :             return fResult;
; 199  :         s_pfn = __IsolationAware_pfn;
; 200  :     }
; 201  :     fResult = __IsolationAware_pfn(dwFlags,lpExtensionGuid,ulSectionId,lpStringToFind,ReturnedData);
; 202  :     return fResult;
; 203  : #endif
; 204  : }
; 205  : 
; 206  : _Success_(return) ISOLATION_AWARE_INLINE BOOL IsolationAwarePrivatenCv IsolationAwareQueryActCtxW(_In_ DWORD dwFlags,_In_ HANDLE hActCtx,_In_opt_ PVOID pvSubInstance,_In_ ULONG ulInfoClass,_Out_writes_bytes_to_opt_(cbBuffer,*pcbWrittenOrRequired) PVOID pvBuffer,_In_ SIZE_T cbBuffer,_Out_opt_ SIZE_T*pcbWrittenOrRequired)
; 207  : {
; 208  : #ifdef _WIN64
; 209  :     return QueryActCtxW(dwFlags,hActCtx,pvSubInstance,ulInfoClass,pvBuffer,cbBuffer,pcbWrittenOrRequired);
; 210  : #else
; 211  :     BOOL fResult = FALSE;
; 212  :     typedef BOOL (WINAPI* PFN)(_In_ DWORD dwFlags,_In_ HANDLE hActCtx,_In_opt_ PVOID pvSubInstance,_In_ ULONG ulInfoClass,_Out_writes_bytes_to_opt_(cbBuffer,*pcbWrittenOrRequired) PVOID pvBuffer,_In_ SIZE_T cbBuffer,_Out_opt_ SIZE_T*pcbWrittenOrRequired);
; 213  :     static PFN s_pfn;
; 214  :     PFN __IsolationAware_pfn = s_pfn;
; 215  :     if (__IsolationAware_pfn == NULL)
; 216  :     {
; 217  :         __IsolationAware_pfn = (PFN) WinbaseIsolationAwarePrivatetRgCebPnQQeRff_xReaRYQP_QYY("QueryActCtxW");
; 218  :         if (__IsolationAware_pfn == NULL)
; 219  :             return fResult;
; 220  :         s_pfn = __IsolationAware_pfn;
; 221  :     }
; 222  :     fResult = __IsolationAware_pfn(dwFlags,hActCtx,pvSubInstance,ulInfoClass,pvBuffer,cbBuffer,pcbWrittenOrRequired);
; 223  :     return fResult;
; 224  : #endif
; 225  : }
; 226  : 
; 227  : _Ret_maybenull_ ISOLATION_AWARE_INLINE HMODULE IsolationAwarePrivatenCv IsolationAwareLoadLibraryExA(_In_ LPCSTR lpLibFileName,_Reserved_ HANDLE hFile,_In_ DWORD dwFlags)
; 228  : {
; 229  :     HMODULE moduleResult = NULL;
; 230  :     ULONG_PTR ulpCookie = 0;
; 231  :     const BOOL fActivateActCtxSuccess =
; 232  :         IsolationAwarePrivateT_SAbnPgpgk ||
; 233  :         IsolationAwarePrivateT_SqbjaYRiRY ||
; 234  :         IsolationAwarePrivatenPgViNgRzlnPgpgk(&ulpCookie);
; 235  :     if (!fActivateActCtxSuccess)
; 236  :         return moduleResult;
; 237  :     __try
; 238  :     {
; 239  :         moduleResult = LoadLibraryExA(lpLibFileName,hFile,dwFlags);
; 240  :     }
; 241  :     __finally
; 242  :     {
; 243  :         if (!IsolationAwarePrivateT_SAbnPgpgk
; 244  :          || !IsolationAwarePrivateT_SqbjaYRiRY
; 245  :         )
; 246  :         {
; 247  :             const BOOL fPreserveLastError = (moduleResult == NULL);
; 248  :             const DWORD dwLastError = fPreserveLastError ? GetLastError() : NO_ERROR;
; 249  :             (void)IsolationAwareDeactivateActCtx(0, ulpCookie);
; 250  :             if (fPreserveLastError)
; 251  :                 SetLastError(dwLastError);
; 252  :         }
; 253  :     }
; 254  :     return moduleResult;
; 255  : }
; 256  : 
; 257  : _Ret_maybenull_ ISOLATION_AWARE_INLINE HMODULE IsolationAwarePrivatenCv IsolationAwareLoadLibraryExW(_In_ LPCWSTR lpLibFileName,_Reserved_ HANDLE hFile,_In_ DWORD dwFlags)
; 258  : {
; 259  :     HMODULE moduleResult = NULL;
; 260  :     ULONG_PTR ulpCookie = 0;
; 261  :     const BOOL fActivateActCtxSuccess =
; 262  :         IsolationAwarePrivateT_SAbnPgpgk ||
; 263  :         IsolationAwarePrivateT_SqbjaYRiRY ||
; 264  :         IsolationAwarePrivatenPgViNgRzlnPgpgk(&ulpCookie);
; 265  :     if (!fActivateActCtxSuccess)
; 266  :         return moduleResult;
; 267  :     __try
; 268  :     {
; 269  :         moduleResult = LoadLibraryExW(lpLibFileName,hFile,dwFlags);
; 270  :     }
; 271  :     __finally
; 272  :     {
; 273  :         if (!IsolationAwarePrivateT_SAbnPgpgk
; 274  :          || !IsolationAwarePrivateT_SqbjaYRiRY
; 275  :         )
; 276  :         {
; 277  :             const BOOL fPreserveLastError = (moduleResult == NULL);
; 278  :             const DWORD dwLastError = fPreserveLastError ? GetLastError() : NO_ERROR;
; 279  :             (void)IsolationAwareDeactivateActCtx(0, ulpCookie);
; 280  :             if (fPreserveLastError)
; 281  :                 SetLastError(dwLastError);
; 282  :         }
; 283  :     }
; 284  :     return moduleResult;
; 285  : }
; 286  : 
; 287  : _Ret_maybenull_ ISOLATION_AWARE_INLINE HMODULE IsolationAwarePrivatenCv IsolationAwareLoadLibraryA(_In_ LPCSTR lpLibFileName)
; 288  : {
; 289  :     HMODULE moduleResult = NULL;
; 290  :     ULONG_PTR ulpCookie = 0;
; 291  :     const BOOL fActivateActCtxSuccess =
; 292  :         IsolationAwarePrivateT_SAbnPgpgk ||
; 293  :         IsolationAwarePrivateT_SqbjaYRiRY ||
; 294  :         IsolationAwarePrivatenPgViNgRzlnPgpgk(&ulpCookie);
; 295  :     if (!fActivateActCtxSuccess)
; 296  :         return moduleResult;
; 297  :     __try
; 298  :     {
; 299  :         moduleResult = LoadLibraryA(lpLibFileName);
; 300  :     }
; 301  :     __finally
; 302  :     {
; 303  :         if (!IsolationAwarePrivateT_SAbnPgpgk
; 304  :          || !IsolationAwarePrivateT_SqbjaYRiRY
; 305  :         )
; 306  :         {
; 307  :             const BOOL fPreserveLastError = (moduleResult == NULL);
; 308  :             const DWORD dwLastError = fPreserveLastError ? GetLastError() : NO_ERROR;
; 309  :             (void)IsolationAwareDeactivateActCtx(0, ulpCookie);
; 310  :             if (fPreserveLastError)
; 311  :                 SetLastError(dwLastError);
; 312  :         }
; 313  :     }
; 314  :     return moduleResult;
; 315  : }
; 316  : 
; 317  : _Ret_maybenull_ ISOLATION_AWARE_INLINE HMODULE IsolationAwarePrivatenCv IsolationAwareLoadLibraryW(_In_ LPCWSTR lpLibFileName)
; 318  : {
; 319  :     HMODULE moduleResult = NULL;
; 320  :     ULONG_PTR ulpCookie = 0;
; 321  :     const BOOL fActivateActCtxSuccess =
; 322  :         IsolationAwarePrivateT_SAbnPgpgk ||
; 323  :         IsolationAwarePrivateT_SqbjaYRiRY ||
; 324  :         IsolationAwarePrivatenPgViNgRzlnPgpgk(&ulpCookie);
; 325  :     if (!fActivateActCtxSuccess)
; 326  :         return moduleResult;
; 327  :     __try
; 328  :     {
; 329  :         moduleResult = LoadLibraryW(lpLibFileName);
; 330  :     }
; 331  :     __finally
; 332  :     {
; 333  :         if (!IsolationAwarePrivateT_SAbnPgpgk
; 334  :          || !IsolationAwarePrivateT_SqbjaYRiRY
; 335  :         )
; 336  :         {
; 337  :             const BOOL fPreserveLastError = (moduleResult == NULL);
; 338  :             const DWORD dwLastError = fPreserveLastError ? GetLastError() : NO_ERROR;
; 339  :             (void)IsolationAwareDeactivateActCtx(0, ulpCookie);
; 340  :             if (fPreserveLastError)
; 341  :                 SetLastError(dwLastError);
; 342  :         }
; 343  :     }
; 344  :     return moduleResult;
; 345  : }
; 346  : 
; 347  : 
; 348  : 
; 349  : #define WINBASE_NUMBER_OF(x) (sizeof(x) / sizeof((x)[0]))
; 350  : 
; 351  : typedef struct IsolationAwarePrivate_pBAFGnAG_zBqHyr_vAsB {
; 352  :     HMODULE (IsolationAwarePrivatenCv * WinbaseIsolationAwarePrivateybNQJ)(_In_ PCWSTR w);
; 353  :     PCWSTR WinbaseIsolationAwarePrivateANZRJ;
; 354  : #ifdef _M_IX86
; 355  :     HMODULE (IsolationAwarePrivatenCv * WinbaseIsolationAwarePrivateybNQn)(_In_ PCSTR w);
; 356  :     PCSTR  WinbaseIsolationAwarePrivateANZRn;
; 357  : #endif
; 358  : } IsolationAwarePrivatepBAFGnAG_zBqHyr_vAsB;
; 359  : typedef const IsolationAwarePrivatepBAFGnAG_zBqHyr_vAsB *IsolationAwarePrivateCpBAFGnAG_zBqHyr_vAsB;
; 360  : 
; 361  : typedef struct IsolationAwarePrivate_zHGnoyr_zBqHyr_vAsB {
; 362  :     HMODULE WinbaseIsolationAwarePrivateybNQRQzbQhYR;
; 363  : } IsolationAwarePrivatezHGnoyr_zBqHyr_vAsB, *IsolationAwarePrivateCzHGnoyr_zBqHyr_vAsB;
; 364  : 
; 365  : ISOLATION_AWARE_INLINE FARPROC IsolationAwarePrivatenCv
; 366  : IsolationAwarePrivatezltRgCebPnQQeRff(
; 367  :     _In_ IsolationAwarePrivateCpBAFGnAG_zBqHyr_vAsB c,
; 368  :     _Inout_ IsolationAwarePrivateCzHGnoyr_zBqHyr_vAsB m,
; 369  :     _In_ PCSTR ProcName
; 370  :     )
; 371  : {
; 372  :     FARPROC Proc = NULL;
; 373  :     HMODULE hModule;
; 374  :     hModule = m->WinbaseIsolationAwarePrivateybNQRQzbQhYR;
; 375  :     if (hModule == NULL)
; 376  :     {
; 377  :         hModule = (*c->WinbaseIsolationAwarePrivateybNQJ)(c->WinbaseIsolationAwarePrivateANZRJ);
; 378  :         if (hModule == NULL)
; 379  :             goto Exit;
; 380  :         m->WinbaseIsolationAwarePrivateybNQRQzbQhYR = hModule;
; 381  :     }
; 382  :     Proc = GetProcAddress(hModule, ProcName);
; 383  : Exit:
; 384  :     return Proc;
; 385  : }
; 386  : 
; 387  : ISOLATION_AWARE_INLINE BOOL IsolationAwarePrivatenCv
; 388  : WinbaseIsolationAwarePrivatetRgzlnPgpgk(void)
; 389  : /*
; 390  : The correctness of this function depends on it being statically
; 391  : linked into its clients.
; 392  : 
; 393  : This function is private to functions present in this header.
; 394  : Do not use it.
; 395  : */
; 396  : {
; 397  :     BOOL fResult = FALSE;
; 398  :     ACTIVATION_CONTEXT_BASIC_INFORMATION actCtxBasicInfo;
; 399  :     ULONG_PTR ulpCookie = 0;
; 400  : 
; 401  :     if (IsolationAwarePrivateT_SqbjaYRiRY)
; 402  :     {
; 403  :         fResult = TRUE;
; 404  :         goto Exit;
; 405  :     }
; 406  : 
; 407  :     if (WinbaseIsolationAwarePrivateT_UnPgpgk != INVALID_HANDLE_VALUE)
; 408  :     {
; 409  :         fResult = TRUE;
; 410  :         goto Exit;
; 411  :     }
; 412  : 
; 413  :     if (!IsolationAwareQueryActCtxW(
; 414  :         QUERY_ACTCTX_FLAG_ACTCTX_IS_ADDRESS
; 415  :         | QUERY_ACTCTX_FLAG_NO_ADDREF,
; 416  :         &WinbaseIsolationAwarePrivateT_UnPgpgk,
; 417  :         NULL,
; 418  :         ActivationContextBasicInformation,
; 419  :         &actCtxBasicInfo,
; 420  :         sizeof(actCtxBasicInfo),
; 421  :         NULL))
; 422  :         goto Exit;
; 423  : 
; 424  :     /*
; 425  :     If QueryActCtxW returns NULL, try CreateActCtx(3).
; 426  :     */
; 427  :     if (actCtxBasicInfo.hActCtx == NULL)
; 428  :     {
; 429  :         ACTCTXW actCtx;
; 430  :         WCHAR rgchFullModulePath[MAX_PATH + 1];
; 431  :         DWORD dw;
; 432  :         HMODULE hmodSelf;
; 433  : #ifdef _M_IX86
; 434  :         PGET_MODULE_HANDLE_EXW pfnGetModuleHandleExW = (PGET_MODULE_HANDLE_EXW)WinbaseIsolationAwarePrivatetRgCebPnQQeRff_xReaRYQP_QYY("GetModuleHandleExW");
; 435  :         if (pfnGetModuleHandleExW == NULL)
; 436  :             goto Exit;
; 437  : #endif
; 438  :         if (!
; 439  : #ifdef _M_IX86
; 440  :             (*pfnGetModuleHandleExW)
; 441  : #else
; 442  :             GetModuleHandleExW
; 443  : #endif
; 444  :             (     GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT
; 445  :                 | GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS,
; 446  :                 (LPCWSTR)&WinbaseIsolationAwarePrivateT_UnPgpgk,
; 447  :                 &hmodSelf))
; 448  :             goto Exit;
; 449  : 
; 450  :         dw = GetModuleFileNameW(hmodSelf, rgchFullModulePath, WINBASE_NUMBER_OF(rgchFullModulePath));
; 451  :         if (dw == 0)
; 452  :             goto Exit;
; 453  :         if (dw >= WINBASE_NUMBER_OF(rgchFullModulePath))
; 454  :         {
; 455  :             SetLastError(ERROR_BUFFER_OVERFLOW);
; 456  :             goto Exit;
; 457  :         }
; 458  : 
; 459  :         actCtx.cbSize = sizeof(actCtx);
; 460  :         actCtx.dwFlags = ACTCTX_FLAG_RESOURCE_NAME_VALID | ACTCTX_FLAG_HMODULE_VALID;
; 461  :         actCtx.lpSource = rgchFullModulePath;
; 462  :         actCtx.lpResourceName = (LPCWSTR)(ULONG_PTR)3;
; 463  :         actCtx.hModule = hmodSelf;
; 464  :         actCtxBasicInfo.hActCtx = IsolationAwareCreateActCtxW(&actCtx);
; 465  :         if (actCtxBasicInfo.hActCtx == INVALID_HANDLE_VALUE)
; 466  :         {
; 467  :             const DWORD dwLastError = GetLastError();
; 468  :             if ((dwLastError != ERROR_RESOURCE_DATA_NOT_FOUND) &&
; 469  :                 (dwLastError != ERROR_RESOURCE_TYPE_NOT_FOUND) &&
; 470  :                 (dwLastError != ERROR_RESOURCE_LANG_NOT_FOUND) &&
; 471  :                 (dwLastError != ERROR_RESOURCE_NAME_NOT_FOUND) &&
; 472  :                 (dwLastError != ERROR_FILE_NOT_FOUND) &&
; 473  :                 (dwLastError != ERROR_PATH_NOT_FOUND))
; 474  :                 goto Exit;
; 475  : 
; 476  :             actCtxBasicInfo.hActCtx = NULL;
; 477  :         }
; 478  : 
; 479  :         WinbaseIsolationAwarePrivateT_SpeRNgRQnPgpgk = TRUE;
; 480  :     }
; 481  : 
; 482  :     WinbaseIsolationAwarePrivateT_UnPgpgk = actCtxBasicInfo.hActCtx;
; 483  : 
; 484  : #define ACTIVATION_CONTEXT_SECTION_DLL_REDIRECTION              (2)
; 485  : 
; 486  :     if (IsolationAwareActivateActCtx(actCtxBasicInfo.hActCtx, &ulpCookie))
; 487  :     {
; 488  :         __try
; 489  :         {
; 490  :             ACTCTX_SECTION_KEYED_DATA actCtxSectionKeyedData;
; 491  : 
; 492  :             actCtxSectionKeyedData.cbSize = sizeof(actCtxSectionKeyedData);
; 493  :             if (IsolationAwareFindActCtxSectionStringW(0, NULL, ACTIVATION_CONTEXT_SECTION_DLL_REDIRECTION, L"Comctl32.dll", &actCtxSectionKeyedData))
; 494  :             {
; 495  :                 /* get button, edit, etc. registered */
; 496  :                 LoadLibraryW(L"Comctl32.dll");
; 497  :             }
; 498  :         }

	push	rbp
	sub	rsp, 64					; 00000040H
	mov	rbp, rdx
$LN23@WinbaseIso:

; 167  :     return DeactivateActCtx(dwFlags,ulCookie);

	mov	rdx, QWORD PTR ulpCookie$[rbp]
	xor	ecx, ecx
	call	QWORD PTR __imp_DeactivateActCtx
	npad	1
$LN24@WinbaseIso:
	add	rsp, 64					; 00000040H
	pop	rbp
	ret	0
	int	3
WinbaseIsolationAwarePrivatetRgzlnPgpgk$fin$0 ENDP
text$x	ENDS
; Function compile flags: /Ogtp
; File c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\winbase.inl
;	COMDAT IsolationAwarePrivatezltRgCebPnQQeRff
_TEXT	SEGMENT
c$ = 48
m$ = 56
ProcName$ = 64
IsolationAwarePrivatezltRgCebPnQQeRff PROC		; COMDAT

; 371  : {

$LN8:
	mov	QWORD PTR [rsp+8], rbx
	push	rdi
	sub	rsp, 32					; 00000020H
	mov	rbx, rdx
	mov	rdi, r8
	mov	rdx, rcx

; 372  :     FARPROC Proc = NULL;
; 373  :     HMODULE hModule;
; 374  :     hModule = m->WinbaseIsolationAwarePrivateybNQRQzbQhYR;

	mov	rax, QWORD PTR [rbx]

; 375  :     if (hModule == NULL)

	test	rax, rax
	jne	SHORT $LN2@IsolationA

; 376  :     {
; 377  :         hModule = (*c->WinbaseIsolationAwarePrivateybNQJ)(c->WinbaseIsolationAwarePrivateANZRJ);

	mov	rcx, QWORD PTR [rcx+8]
	call	QWORD PTR [rdx]

; 378  :         if (hModule == NULL)

	test	rax, rax
	je	SHORT $LN6@IsolationA

; 379  :             goto Exit;
; 380  :         m->WinbaseIsolationAwarePrivateybNQRQzbQhYR = hModule;

	mov	QWORD PTR [rbx], rax
$LN2@IsolationA:

; 381  :     }
; 382  :     Proc = GetProcAddress(hModule, ProcName);

	mov	rdx, rdi
	mov	rcx, rax
$Exit$9:

; 383  : Exit:
; 384  :     return Proc;
; 385  : }

	mov	rbx, QWORD PTR [rsp+48]
	add	rsp, 32					; 00000020H
	pop	rdi

; 381  :     }
; 382  :     Proc = GetProcAddress(hModule, ProcName);

	rex_jmp	QWORD PTR __imp_GetProcAddress

; 383  : Exit:
; 384  :     return Proc;
; 385  : }

$LN6@IsolationA:
	mov	rbx, QWORD PTR [rsp+48]
	add	rsp, 32					; 00000020H
	pop	rdi
	ret	0
IsolationAwarePrivatezltRgCebPnQQeRff ENDP
_TEXT	ENDS
; Function compile flags: /Ogtp
; File c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\winbase.inl
;	COMDAT IsolationAwareQueryActCtxW
_TEXT	SEGMENT
dwFlags$ = 8
hActCtx$ = 16
pvSubInstance$ = 24
ulInfoClass$ = 32
pvBuffer$ = 40
cbBuffer$ = 48
pcbWrittenOrRequired$ = 56
IsolationAwareQueryActCtxW PROC				; COMDAT

; 208  : #ifdef _WIN64
; 209  :     return QueryActCtxW(dwFlags,hActCtx,pvSubInstance,ulInfoClass,pvBuffer,cbBuffer,pcbWrittenOrRequired);

	rex_jmp	QWORD PTR __imp_QueryActCtxW
IsolationAwareQueryActCtxW ENDP
_TEXT	ENDS
; Function compile flags: /Ogtp
; File c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\winbase.inl
;	COMDAT IsolationAwareFindActCtxSectionStringW
_TEXT	SEGMENT
dwFlags$ = 8
lpExtensionGuid$ = 16
ulSectionId$ = 24
lpStringToFind$ = 32
ReturnedData$ = 40
IsolationAwareFindActCtxSectionStringW PROC		; COMDAT

; 187  : #ifdef _WIN64
; 188  :     return FindActCtxSectionStringW(dwFlags,lpExtensionGuid,ulSectionId,lpStringToFind,ReturnedData);

	rex_jmp	QWORD PTR __imp_FindActCtxSectionStringW
IsolationAwareFindActCtxSectionStringW ENDP
_TEXT	ENDS
; Function compile flags: /Ogtp
; File c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\winbase.inl
;	COMDAT IsolationAwareDeactivateActCtx
_TEXT	SEGMENT
dwFlags$ = 8
ulCookie$ = 16
IsolationAwareDeactivateActCtx PROC			; COMDAT

; 166  : #ifdef _WIN64
; 167  :     return DeactivateActCtx(dwFlags,ulCookie);

	rex_jmp	QWORD PTR __imp_DeactivateActCtx
IsolationAwareDeactivateActCtx ENDP
_TEXT	ENDS
; Function compile flags: /Ogtp
; File c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\winbase.inl
;	COMDAT IsolationAwareActivateActCtx
_TEXT	SEGMENT
hActCtx$ = 8
lpCookie$ = 16
IsolationAwareActivateActCtx PROC			; COMDAT

; 145  : #ifdef _WIN64
; 146  :     return ActivateActCtx(hActCtx,lpCookie);

	rex_jmp	QWORD PTR __imp_ActivateActCtx
IsolationAwareActivateActCtx ENDP
_TEXT	ENDS
; Function compile flags: /Ogtp
; File c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\winbase.inl
;	COMDAT IsolationAwareCreateActCtxW
_TEXT	SEGMENT
pActCtx$ = 8
IsolationAwareCreateActCtxW PROC			; COMDAT

; 104  : #ifdef _WIN64
; 105  :     return CreateActCtxW(pActCtx);

	rex_jmp	QWORD PTR __imp_CreateActCtxW
IsolationAwareCreateActCtxW ENDP
_TEXT	ENDS
; Function compile flags: /Ogtp
; File c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\winbase.inl
;	COMDAT IsolationAwarePrivatenPgViNgRzlnPgpgk
_TEXT	SEGMENT
pulpCookie$ = 48
IsolationAwarePrivatenPgViNgRzlnPgpgk PROC		; COMDAT

; 582  : {

$LN21:
	push	rbx
	sub	rsp, 32					; 00000020H

; 583  :     BOOL fResult = FALSE;
; 584  : 
; 585  :     if (WinbaseIsolationAwarePrivateT_SpYRNahcpNYYRQ)

	mov	eax, DWORD PTR WinbaseIsolationAwarePrivateT_SpYRNahcpNYYRQ
	mov	rbx, rcx
	test	eax, eax
	je	SHORT $LN2@IsolationA

; 586  :     {
; 587  :         const static char debugString[] = "IsolationAware function called after IsolationAwareCleanup\n";
; 588  :         OutputDebugStringA(debugString);

	lea	rcx, OFFSET FLAT:?debugString@?4??IsolationAwarePrivatenPgViNgRzlnPgpgk@@9@4QBDB ; `IsolationAwarePrivatenPgViNgRzlnPgpgk'::`5'::debugString
	call	QWORD PTR __imp_OutputDebugStringA
	mov	eax, DWORD PTR WinbaseIsolationAwarePrivateT_SpYRNahcpNYYRQ
$LN2@IsolationA:

; 589  :     }
; 590  : 
; 591  :     if (IsolationAwarePrivateT_SqbjaYRiRY)

	cmp	DWORD PTR IsolationAwarePrivateT_SqbjaYRiRY, 0
	jne	SHORT $LN19@IsolationA

; 592  :     {
; 593  :         fResult = TRUE;
; 594  :         goto Exit;
; 595  :     }
; 596  : 
; 597  :     /* Do not call Init if Cleanup has been called. */
; 598  :     if (!WinbaseIsolationAwarePrivateT_SpYRNahcpNYYRQ)

	test	eax, eax
	jne	SHORT $LN6@IsolationA

; 599  :     {
; 600  :         if (!WinbaseIsolationAwarePrivatetRgzlnPgpgk())

	call	WinbaseIsolationAwarePrivatetRgzlnPgpgk
	test	eax, eax
	je	SHORT $LN16@IsolationA
$LN6@IsolationA:

; 146  :     return ActivateActCtx(hActCtx,lpCookie);

	mov	rcx, QWORD PTR WinbaseIsolationAwarePrivateT_UnPgpgk
	mov	rdx, rbx
	call	QWORD PTR __imp_ActivateActCtx

; 601  :             goto Exit;
; 602  :     }
; 603  :     /* If Cleanup has been called and id3 was in use, this will activate NULL. */
; 604  :     if (!IsolationAwareActivateActCtx(WinbaseIsolationAwarePrivateT_UnPgpgk, pulpCookie))

	test	eax, eax
	jne	SHORT $LN19@IsolationA
$LN16@IsolationA:

; 605  :         goto Exit;
; 606  : 
; 607  :     fResult = TRUE;
; 608  : Exit:
; 609  :     if (!fResult)
; 610  :     {
; 611  :         const DWORD dwLastError = GetLastError();

	call	QWORD PTR __imp_GetLastError
	lea	ecx, DWORD PTR [rax-126]
	cmp	ecx, 1
	jbe	SHORT $LN12@IsolationA
	cmp	eax, 120				; 00000078H
	je	SHORT $LN12@IsolationA
	cmp	eax, 1
	je	SHORT $LN12@IsolationA
	cmp	eax, 50					; 00000032H
	je	SHORT $LN12@IsolationA

; 619  :             fResult = TRUE;
; 620  :         }
; 621  :     }
; 622  :     return fResult;

	xor	eax, eax

; 623  : }

	add	rsp, 32					; 00000020H
	pop	rbx
	ret	0
$LN12@IsolationA:

; 612  :         if (dwLastError == ERROR_PROC_NOT_FOUND
; 613  :             || dwLastError == ERROR_MOD_NOT_FOUND
; 614  :             || dwLastError == ERROR_CALL_NOT_IMPLEMENTED
; 615  :             || dwLastError == ERROR_INVALID_FUNCTION
; 616  :             || dwLastError == ERROR_NOT_SUPPORTED)
; 617  :         {
; 618  :             IsolationAwarePrivateT_SqbjaYRiRY = TRUE;

	mov	DWORD PTR IsolationAwarePrivateT_SqbjaYRiRY, 1
$LN19@IsolationA:

; 619  :             fResult = TRUE;
; 620  :         }
; 621  :     }
; 622  :     return fResult;

	mov	eax, 1

; 623  : }

	add	rsp, 32					; 00000020H
	pop	rbx
	ret	0
IsolationAwarePrivatenPgViNgRzlnPgpgk ENDP
_TEXT	ENDS
; Function compile flags: /Ogtp
; File c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\winbase.inl
;	COMDAT IsolationAwarePrivatezlybNQyVOeNelJ
_TEXT	SEGMENT
s$ = 8
IsolationAwarePrivatezlybNQyVOeNelJ PROC		; COMDAT

; 57   : ISOLATION_AWARE_INLINE HMODULE IsolationAwarePrivatenCv IsolationAwarePrivatezlybNQyVOeNelJ(_In_ PCWSTR s) { return LoadLibraryW(s); }

	rex_jmp	QWORD PTR __imp_LoadLibraryW
IsolationAwarePrivatezlybNQyVOeNelJ ENDP
_TEXT	ENDS
; Function compile flags: /Ogtp
; File g:\dropbox\github\berconmaps\src\dllentry.cpp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT

	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Ogtp
; File g:\dropbox\github\berconmaps\src\dllentry.cpp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT

	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ??_H@YAXPEAX_K1P6APEAX0@Z@Z
_TEXT	SEGMENT
__t$ = 48
__s$ = 56
__n$ = 64
__f$ = 72
??_H@YAXPEAX_K1P6APEAX0@Z@Z PROC			; `vector constructor iterator', COMDAT
$LN12:
	test	r8, r8
	je	SHORT $LN10@vector
	mov	QWORD PTR [rsp+8], rbx
	mov	QWORD PTR [rsp+16], rbp
	mov	QWORD PTR [rsp+24], rsi
	push	rdi
	sub	rsp, 32					; 00000020H
	mov	rsi, r9
	mov	rbx, r8
	mov	rbp, rdx
	mov	rdi, rcx
$LL2@vector:
	mov	rcx, rdi
	call	rsi
	add	rdi, rbp
	sub	rbx, 1
	jne	SHORT $LL2@vector
	mov	rbx, QWORD PTR [rsp+48]
	mov	rbp, QWORD PTR [rsp+56]
	mov	rsi, QWORD PTR [rsp+64]
	add	rsp, 32					; 00000020H
	pop	rdi
$LN10@vector:
	ret	0
??_H@YAXPEAX_K1P6APEAX0@Z@Z ENDP			; `vector constructor iterator'
_TEXT	ENDS
END
